### ISSUE TITLE
Do or could theses work in 11th gen servers?

### ISSUE THREAD

**Issue by BillDStrong** [Fohdeesha/lab-docu#10]
So, I want to try this out, but I have an r610. Will these cards work in the storage slot, or the regular pci slot if I ordered this card. (It is an obvious upgrade over the cards supported for the 11th gen servers.)

I can't seem to find any info about them working or not after looking for a few days. I like to think my Google Fu is good, but I am stumped.

In particular, I guess I am asking is does the r610 look for the same vendor ids in the card, and if not, could we modify them to match what the r610 is expecting. What could I do to help such an effort, if it is required. 

I currently have a stock Dell PERC 6i in the system, if the info from it would be useful.

Thanks in advance for any help provided.

**Comment by Fohdeesha** [comment]
The 12th gen cards that this guide is for are totally different than the 11g cards (in size, connector, and everything), they will not work anywhere else but a 12g dell server. If you need a SAS raid card and have a free pci-e slot, it's much easier and cheaper to just buy the actual LSI card that these dell cards are based off of, so you don't have to deal with crossflashing. This guide was born because people were out of PCI-E slots and `had` to use the built in storage slot, and needed disk passthrough in IT mode, not RAID. If you have the option, an actual LSI card is cheaper and easier. For example, search ebay for a 9211-8i for example: https://www.ebay.com/itm/Fujitsu-9211-8i-D2607-A21-6Gbps-SAS-LSISAS2008-P20-IT-Mode-ZFS-FreeNAS-unRAID-US/192934435038

This is all assuming you don't want RAID, but dumb disk passthrough in IT mode for something like ZFS

**Comment by BillDStrong** [comment]
My goal was to buy a few and flash them, sell the ones I don't need on ebay to break even, and use my storage slot. My PCI-E slots are already used, unfortunately. 

The goal is IT mode, for Proxmox. I wanted to buy something that might stick around for my next build when I save up the cash. :)

So I guess I can ask if the h310 mini would fit. It is essentially the h200, which is a supported board for the 11th gen. But the h710 still would be nice.

Thanks again for your help.

**Comment by Fohdeesha** [comment]
None of the 12g cards will work (h310 mini, h710 mini, etc). The size is massively different and they both have completely different connectors and interfaces

**Comment by BillDStrong** [comment]
Well, thanks for your help. When you say the interfaces are different, are you talking about the PCI-E x4 slot, or the firmware? 

I will close this issue, unless you think it might prevent others asking you these stupid questions. :)

Thanks again for your help.

**Comment by Fohdeesha** [comment]
I mean the physical connector and formfactor. Just do a Google image search for "h310 mini" and then "perc6i" and you'll see what I mean
