### ISSUE TITLE
Disks letter problems

### ISSUE THREAD

**Issue by gabrielwz** [Fohdeesha/lab-docu#19]
Hello,
We have the PERC H710 Mini controller with its firmware installed, and for the file system we use zfs.
The problem we have is that every time the computer restarts, the letters change on the disks randomly causing the pool to become unusable.

Is there a way to set the letters of the disks permanent?

Thanks

**Comment by Fohdeesha** [comment]
Hi, this is not an issue with my guide or firmware - this is normal behavior and disks are never guaranteed to keep the same device names.

Because of this you should never create pools based on disk letters or device names, this is what disk GUIDs are for, those do not change. Your pool needs to be created using UUIDs: 

https://www.reddit.com/r/zfs/comments/i9w05d/switching_from_devsdx_to_devdiskbyuuid/
https://unix.stackexchange.com/questions/519653/zfs-replace-disks-by-id
