### ISSUE TITLE
Hard-drives' status and activity led off after flashing LSI firmware

### ISSUE THREAD

**Issue by marius-nicolae** [Fohdeesha/lab-docu#8]
Hi,

After flashing the LSI firmware for an H710P Mini D1 on a Dell Poweredge R720, by following the guide from https://fohdeesha.com/docs/H710P-D1/ , both status and activity LEDs from all hard-drives are off all the time. The hard-drives are correctly identified by the bios and OS and function normally. 

Did anyone encounter this situation? What would be the cause and how can it be fixed?

Thanks!

**Comment by kaminet** [comment]
For me status LEDs also does not work.
They never light up, even when locating drive from UEFI:
- Launch System Setup
- Device Settings
- Integrated ...
- LSI SAS2 ...
- Physical Disk Management
- Select ...
- Start Locate / Blink

Drive activity LEDs more or less working.
For SAS HDD LEDs are ON and BLINK for activity
For SATA SSD LEDs are OFF and BLINK for activity (initially ON on boot)
For SATA HDD LEDs does not work, always OFF

In my case Drive Bay numbers are reversed. 0 <=> 7

**Comment by Moxified** [comment]
Same issue.  Activity LED seem to work but status LED are dark and bay numbers are reversed.  H710 mini D1 in an R420.

**Comment by Fohdeesha** [comment]
Hi, this is expected behavior and there's nothing we can do about it. The crossflashed LSI card is working properly and sending the signalling commands for LEDs over the SAS connection, however the dell backplane ignores these and expects proprietary control commands over a totally separate serial connection from IDRAC (you can see the separate connector towards the right side of the backplane, connecting to the rear area of the motherboard). Obviously the LSI card is going to be totally unaware of this. This is the same reason the drive order is presented strangely, the backplane presents the drive bays in a very strange order that the dell firmware was programmed to "straighten out", and of course the OEM lsi firmware will not do this
