### ISSUE TITLE
H710 D1 mini flash Live Linux CD doesn't auto-select Live CD

### ISSUE THREAD

**Issue by jhughes2112** [Fohdeesha/lab-docu#9]
I had a monitor that didn't like Linux VGA output very well, so I ran into a problem with this.  I used IPMI to reboot/login/modify most stuff, but the live CD menu doesn't come across IPMI, and my monitor was busted, so I had to buy a ratty old one and plug it in to figure out why it was stalling out.  Whatev, I needed one for the occasional use.  At least in my case, I had to physically hit enter on the box.  This is a super-minor quibble, and not terribly interesting to fix.  

What I really wanted to do was THANK YOU for putting this project and making it available for others to use.  If there was a place to thumbs-up on your website (the guide is great, btw), or here, I would have.

Best regards

**Comment by Fohdeesha** [comment]
thanks for the report! Indeed, for some reason the debian live boot selection doesn't have a default timeout, you HAVE to hit enter. I never had the time to investigate why and now my build environment for the live ISO is tore down :/

**Comment by Fohdeesha** [comment]
going to try and fix this when I build a new linux ISO in a week or two

**Comment by Fohdeesha** [comment]
have this fixed, will be publishing the new ISO in a couple days. Thanks for the report!

**Comment by Fohdeesha** [comment]
fixed via https://github.com/Fohdeesha/lab-docu/commit/4d6b5d24a78e834190fe4f87492e82ba1c865bdb and https://github.com/Fohdeesha/lab-docu/commit/1887fbafa8d430517970127291e6a1dd21fcfa0e#diff-28ecfcf691fd621b07872269dec57af9773437371881f10978677c9ef1d8846c  

the `isolinux` bootloader is used when MBR/BIOS booting the ISO, and `grub` is used when UEFI booting - people should only be booting this ISO via MBR/BIOS boot if they're following the guide correctly, but I went ahead and updated the config of both bootloaders to have a timeout of 5 seconds instead of infinite (isolinux timeout values are in tenths of seconds, which is why I have it set to 50 instead of 5) - after 5 seconds they will default to booting the ISO. The new 1.9 ISO package is now live on the docs site with these changes. Thanks again for the report!
